# Updated to Live Railway Cloud Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Spring JPA Settings
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=${SERVER_PORT}

# Modern Email API Configuration
brevo.api.key=${BREVO_API_KEY}
